# Generated by Django 3.1 on 2020-08-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('summary', models.TextField(max_length=2000)),
                ('skills', models.TextField(max_length=2000)),
                ('education', models.TextField(max_length=2000)),
                ('jobs', models.TextField(max_length=2000)),
            ],
        ),
    ]
